set-option -sg escape-time 10
set-option -g focus-events on
set-option -a terminal-features 'xterm-256color:RGB'


# Start windows numbering at 1
set -g base-index 1
# Start panes numbering at 1
setw -g pane-base-index 1
# Ensure window index numbers get reordered automatically when a window is closed
set-option -g renumber-windows on
# toggle status bar
bind-key t set-option -g status

# keymaps
# Change leader to Ctrl+Space
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# styling
gray_light="#D8DEE9"
green_soft="#A3BE8C"
cyan_soft="#88C0D0"
dark_green="#141b1e"
battery_percentage="cat /sys/class/power_supply/BAT0/capacity"
# set -g status-position top
set -g status-left-length 100
set -g status-style "bg=${dark_green}"
set -g status-left "#[fg=${green_soft},bold]  #S #[fg=${gray_light},nobold] |"
set -g status-right '#[fg=green]|#[fg=white] %a %d %b %I:%M%p #[fg=green]| #[fg=white]󱊣 #(${battery_percentage}) %'
set -g window-status-current-format "#[fg=${cyan_soft},bold] #[underscore]#W"
set -g window-status-format " #I:#W"

# Place the pane border at the bottom of the pane
set-window-option -g pane-border-status bottom

# Optional: Customize the appearance of this line
# Use the '─' character for a continuous horizontal line
set-window-option -g pane-border-format '─'

# Optional: Customize the style of the border line (e.g., color)
# set-option -g pane-active-border-style fg=${gray_light}

